site_name: 'DDBstudio-Handbuch'
site_description: 'Virtuelle Ausstellungen der Deutschen Digitalen Bibliothek'
site_author: 'Deutsche Digitale Bibliothek, Culture to Go & Grandgeorg Websolutions'

# Copyright
copyright: ''

# Structure
nav:
    - Einleitung: einleitung.md
    - Projekt starten: projekt_starten.md
    - A So funktioniert DDBStudio: 
      - 1. Die fertige Ausstellung - das Frontend: frontend.md
      - 2. Das Omeka Backend: backend.md
    - B Die Exponate - Objekte in Omeka:
      - 1. Objekte in DDBStudio: objekte.md
      - 2. Objekte erstellen: objekte_erstellen.md
      - 3. Metadaten: objekte_metadaten.md
      - 4. Medien: objekte_medien.md
      - 5. Objekte suchen: objekte_suche.md
    - C Die Ausstellung:
      - 1. Die Ausstellung anlegen: ausstellung_anlegen.md
      - 2. Seiten anlegen: seiten_anlegen.md
      - 3. Seiten-Layouts: seiten_layouts.md
      - 4. Die zweite Dimension - Slider: slider.md
    - D Anhang:
      - 1. Metadaten der Objekte: anhang_metadaten.md
      - 2. Der Texteditor: anhang_editor.md
      - 3. Mediendateien: anhang_mediendateien.md
    - Impressum: impressum.md

# Theme
theme:
  name: readthedocs
  custom_dir: themes/readthedocs_ddb
  highlightjs: False

# Options
extra:
  wording_next: 'vor'
  wording_previous: 'zurück'
  wording_search_docs: 'Handbuch durchsuchen'
  wording_docs: 'DDB-Handbuch-Vorlage'
  wording_page_not_found: 'Seite nicht gefunden.'

#css
extra_css:
    - css/extra.css

# js
extra_javascript:
    - js/extra.js

# URL
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: True
  - sane_lists
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - figureAltCaption